name: 'Set Env'
description: 'Set environment variables'
author: 'qoomon'
branding:
  icon: box
  color: blue

inputs:
  vars:
    description: 'GitHub vars as json e.g. $ {{ toJson(vars) }}'
  secrets:
    description: 'GitHub secrets as json e.g. $ {{ toJson(secrets) }}'
  scope:
    description: 'Variable scope e.g. PROD'
  export:
    description: 'Variables to export as comma and/or new line separated list'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
